apiVersion: v1
kind: PersistentVolume
metadata:
  name: safari-pv
spec:
  capacity:
     storage: 2Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  accessModes:
     - ReadWriteOnce
  hostPath:
     path: /tmp/Data
